Fixing build for MSVC.
hunter-packages/SDL2 pull request #4
Opened 2017-12-22 18:00 UTC by Predelnik

Since I don't know what exactly is wrong I'm playing a bit of guessing game here. But I've tried to apply your suggestions.

Maybe if it doesn't work I need to learn how to test things locally.

2017-12-22 18:48 UTC, ruslo requested changes
> Maybe if it doesn't work I need to learn how to test things locally

Testing locally described here:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally

Note that in current workflow you should test new version of package remotely youself before submitting it to main repository:
* https://docs.hunter.sh/en/latest/creating-new/update.html#testing

Meaning that situation when some toolchains failed like in https://github.com/ruslo/hunter/pull/1270 should not happen.

2017-12-22 18:48 UTC, ruslo commented on CMakeLists.txt
>    set(PKG_PREFIX "SDL2.framework/Resources")
I guess this line should be fixed too. `lib/cmake/SDL2` will work for all cases.

2017-12-22 18:48 UTC, ruslo commented on CMakeLists.txt
>    set(PKG_PREFIX "SDL2.framework/Resources")
> ${CMAKE_CURRENT_SOURCE_DIR}/SDL2Config.cmake

This should be removed. Config generated from `cmake/Config.cmake.in`.

2017-12-23 15:10 UTC, Predelnik commented
So I've managed to run CI on my fork. After proposed changes, looks good:
https://ci.appveyor.com/project/Predelnik/hunter/build/1.0.2
https://travis-ci.org/Predelnik/hunter

2017-12-23 15:27 UTC, ruslo approved these changes

2017-12-23 15:28 UTC, merged

2017-12-23 15:28 UTC, ruslo commented
Released: https://github.com/hunter-packages/SDL2/releases/tag/v2.0.7-p1